version: "3.9"

services:
  mangaverse-web:
    build:
      context: .
      dockerfile: deploy/docker/Dockerfile
    container_name: mangaverse-web
    ports:
      - "40141:40141"
    volumes:
      # Mount exported site on the host into the container's web root
      - /mangaverse:/usr/share/nginx/html:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:40141/" ]
      interval: 30s
      timeout: 5s
      retries: 3
