version: "3.9"

services:
  mangaverse-web:
    build:
      context: ../..
      dockerfile: deploy/docker/Dockerfile
    container_name: mangaverse-web
    # Use host networking to ensure the service is reachable on IPv6 [::]:40141
    network_mode: host
    volumes:
      - /mangaverse:/usr/share/nginx/html:ro
    restart: unless-stopped
